from subprocess import Popen, PIPE, check_output, STDOUT
import datetime
fulltimestamp=datetime.datetime.now().strftime('%Y%m%d_%H-%M-%S')

with open('\logs\post_processing_csi_error_'+fulltimestamp+'.txt', 'w') as e:
    #f.flush()
    #e.flush()
    proc = Popen(['python', 'vol_adjsize_c2.py','1'], stderr=e)
    proc.wait()
    e.flush()
    proc = Popen(['python', 'vol_adjsize.py','1'], stderr=e)
    proc.wait()
    e.flush()
    proc = Popen(['python', 'refresh_c2.py','1'], stderr=e)
    proc.wait()
    e.flush()
    proc = Popen(['python', 'slip_report_c2.py','1'], stderr=e)
    proc.wait()
    e.flush()
    proc = Popen(['python', 'slip_report_ib.py','1'], stderr=e)
    proc.wait()
    e.flush()
    proc = Popen(['python', 'heatmap_futuresCSI.py','1'], stderr=e)
    proc.wait()
    e.flush()
    proc = Popen(['python', 'run_allsystems.py','1'], stderr=e)
    proc.wait()
    e.flush()
    proc = Popen(['python', 'vol_adjsize.py','1'], stderr=e)
    proc.wait()
