# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-20 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currenciesATR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pairs', models.CharField(max_length=100)),
                ('Last', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'currenciesATR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CSIsym', models.CharField(max_length=100)),
                ('Desc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Dictionary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(default='media/default.png', upload_to='treasure_images')),
            ],
        ),
    ]
