# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselection',
            name='mcdate',
            field=models.TextField(),
        ),
    ]
