# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(db_index=True, null=True)),
                ('date', models.DateTimeField(db_index=True, null=True)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('crawl_source', models.CharField(blank=True, default=b'', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(db_index=True, max_length=255, null=True)),
                ('sym', models.CharField(db_index=True, max_length=255, null=True)),
                ('cur', models.CharField(db_index=True, max_length=255, null=True)),
                ('exch', models.CharField(db_index=True, max_length=255, null=True)),
                ('secType', models.CharField(db_index=True, max_length=255, null=True)),
                ('trade_freq', models.IntegerField(db_index=True, null=True)),
                ('mult', models.IntegerField(db_index=True, null=True)),
                ('local_sym', models.CharField(db_index=True, max_length=255, null=True)),
                ('contractMonth', models.IntegerField(db_index=True, null=True)),
                ('expiry', models.CharField(db_index=True, max_length=255, null=True)),
                ('evRule', models.CharField(db_index=True, max_length=255, null=True)),
                ('liquidHours', models.CharField(db_index=True, max_length=255, null=True)),
                ('longName', models.CharField(db_index=True, max_length=255, null=True)),
                ('minTick', models.FloatField(db_index=True, max_length=255, null=True)),
                ('timeZoneId', models.IntegerField(db_index=True, null=True)),
                ('tradingHours', models.CharField(db_index=True, max_length=255, null=True)),
                ('underConId', models.IntegerField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('crawl_source', models.CharField(blank=True, default=b'', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=255, null=True)),
                ('system', models.CharField(db_index=True, max_length=255, null=True)),
                ('name', models.CharField(db_index=True, max_length=255, null=True)),
                ('c2id', models.CharField(db_index=True, max_length=255, null=True)),
                ('c2api', models.CharField(db_index=True, max_length=255, null=True)),
                ('c2qty', models.IntegerField(db_index=True, null=True)),
                ('c2submit', models.BooleanField(default=False)),
                ('ibqty', models.IntegerField(db_index=True, null=True)),
                ('ibsubmit', models.BooleanField(default=False)),
                ('trade_freq', models.IntegerField(db_index=True, null=True)),
                ('ibmult', models.IntegerField(db_index=True, null=True)),
                ('c2mult', models.IntegerField(db_index=True, null=True)),
                ('signal', models.CharField(db_index=True, max_length=255, null=True)),
                ('c2instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c2instrument', to='feed.Instrument')),
                ('ibinstrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ibinstrument', to='feed.Instrument')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Instrument'),
        ),
    ]
