# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('selection', models.TextField()),
                ('v4futures', models.TextField()),
                ('v4mini', models.TextField()),
                ('v4micro', models.TextField()),
                ('mcdate', models.DateTimeField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
    ]
