# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20161208_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountvalues', models.TextField()),
                ('urpnls', models.TextField()),
                ('mcdate', models.TextField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.TextField()),
                ('triggers', models.TextField()),
                ('mcdate', models.TextField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
    ]
