# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_auto_20161215_0631'),
        ('betting', '0004_auto_20161214_1228'),
    ]

    operations = [
    ]
